# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/son_link/proyectos/PQMusic/PQMusic/ui/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config_Dialog(object):
    def setupUi(self, Config_Dialog):
        Config_Dialog.setObjectName("Config_Dialog")
        Config_Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Config_Dialog.resize(365, 202)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Config_Dialog.setWindowIcon(icon)
        Config_Dialog.setToolTip("")
        Config_Dialog.setWhatsThis("")
        Config_Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Config_Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Config_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Config_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.minimizeToTray = QtWidgets.QCheckBox(Config_Dialog)
        self.minimizeToTray.setObjectName("minimizeToTray")
        self.gridLayout.addWidget(self.minimizeToTray, 3, 0, 1, 3)
        self.notifyOnChange = QtWidgets.QCheckBox(Config_Dialog)
        self.notifyOnChange.setObjectName("notifyOnChange")
        self.gridLayout.addWidget(self.notifyOnChange, 2, 0, 1, 3)
        self.musicFolderEdit = QtWidgets.QLineEdit(Config_Dialog)
        self.musicFolderEdit.setObjectName("musicFolderEdit")
        self.gridLayout.addWidget(self.musicFolderEdit, 1, 0, 1, 1)
        self.setMusicFolderBtn = QtWidgets.QPushButton(Config_Dialog)
        self.setMusicFolderBtn.setObjectName("setMusicFolderBtn")
        self.gridLayout.addWidget(self.setMusicFolderBtn, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Config_Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Config_Dialog)
        self.buttonBox.accepted.connect(Config_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Config_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Config_Dialog)

    def retranslateUi(self, Config_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Config_Dialog.setWindowTitle(_translate("Config_Dialog", "Config PQMusic"))
        self.minimizeToTray.setText(_translate("Config_Dialog", "Minimize to system tray when closing window"))
        self.notifyOnChange.setText(_translate("Config_Dialog", "Show notifications when changing songs"))
        self.setMusicFolderBtn.setText(_translate("Config_Dialog", "Select folder"))
        self.label.setText(_translate("Config_Dialog", "Default music folder:"))
from . import images_rc
